;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-pair-delete-pair
        ))

(setq mc/cmds-to-run-once
      '(
        electric-newline-and-maybe-indent
        eval-print-last-sexp
        ))
