;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        Buffer-menu-delete
        electric-pair-delete-pair
        indent-for-tab-command
        iy-go-to-char--command
        kill-region
        paredit-backslash
        paredit-backward-kill-word
        paredit-close-round
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        paredit-newline
        paredit-open-round
        paredit-semicolon
        smart-open-line-above
        smarter-move-beginning-of-line
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        electric-newline-and-maybe-indent
        eval-print-last-sexp
        ))
