#+TITLE: README
#+AUTHOR: John Ankarström
#+DATE: 2014-05-13
#+EMAIL: john.ankarstrom@gmail.com

* =emacs.d=

Welcome to my =emacs.d= directory.  I'm traditionally a Vim user, but I thought I'd try Emacs out.  This directory is created from scratch and I expand it as I go along.

** Current Structure

- In =init.d=, I call initialize the server and load all packages in the =packages/= directory.
- In =personal.d=, I put useful commands I've created or found on the web, as well as preferences, such as colorscheme.

** What I Think So Far

I like a lot of things about Emacs.  It's a nice environment to type in.  Most of all, I like Elisp.  VimScript can be useful, but Elisp feels a thousand times more useful and logical.  I do, however, miss many things from Vim.  I miss the short commands (seriously, =C-a C-k C-k C-y C-y= to duplicate a line compared to =yyp=) and the ability to combine commands (=dw=, =dd=, =de=, =db=, and so forth--much less clunky than =C-d= and =C-k=).

I'm certainly much faster in Vim, but that might change.
